### ISSUE TITLE
Fatal error. System.Runtime.InteropServices.SEHException

### ISSUE THREAD

**Issue by K1tiK4** [SciSharp/LLamaSharp#606] opened 2024-03-17 11:12 UTC
When trying to run a model on CUDA 12, a fatal error occurs
![image](https://github.com/SciSharp/LLamaSharp/assets/111649965/d37f4fb7-dc00-4cb6-9045-0d0124209d14)

**Comment by AsakusaRinne** [comment] 2024-03-17 12:47
Hi, which version of LLamaSharp and dotnet runtime are you using?

**Comment by K1tiK4** [comment] 2024-03-17 16:28
![image](https://github.com/SciSharp/LLamaSharp/assets/111649965/25f9c751-f3e0-42ba-b927-d3428ec1debf)

**Comment by AsakusaRinne** [comment] 2024-03-17 16:43
Could you please check your model path again to confirm it's the right path?

**Comment by K1tiK4** [comment] 2024-03-17 16:50
The model path is definitely correct since everything is running on the processor back end.

**Comment by AsakusaRinne** [comment] 2024-03-17 17:09
OK, then could you please take a try with the master branch code? There've been many commits ahead of v0.10.0 now. If the error still appears, please give us a minimal example to reproduce it and we'll dig on this problem.

**Comment by K1tiK4** [comment] 2024-03-17 17:20
Okay, I'll try now

**Comment by K1tiK4** [comment] 2024-03-17 18:04
I tried updating net core to 8.0, but nothing changed. The code was taken from the quick start example. Here are the specs of the PC it runs on. Maybe this will help find the problem
Processor: AMD FX 8320
GPU: GTX 1660 super
RAM: 16 GB
OS: Windows 10 pro
![image](https://github.com/SciSharp/LLamaSharp/assets/111649965/6db3a709-2aa8-4108-8c81-c1f61c268f7c)

**Comment by K1tiK4** [comment] 2024-03-17 18:09
The same error in the example from master
![image](https://github.com/SciSharp/LLamaSharp/assets/111649965/0ac34aed-cc0c-4050-bca9-06c32b99e0b9)

**Comment by AsakusaRinne** [comment] 2024-03-17 18:40
Hi, I think I've found the problem. Your cpu is a bit old (released in 2012) so I think it has no avx support, while our cuda backend is compiled with avx2 by default.

Firstly, you could confirm this point by installing cpu backend and add this line to the beginning of your code. (with v0.10, not master)

```cs
using LLama.Native;
NativeLibraryConfig.WithLogs();
```

Then, you'll see which level avx of the native library is selected by default.

If it's confirmed that your PC has no avx support or does not support avx, please follow the steps to fix it:
1. clone llama.cpp repo and enter its directory.
2. `mkdir build && cd build`
3. `cmake -DBUILD_SHARED_LIBS=ON -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_EXAMPLES=ON -DLLAMA_AVX=OFF -DLLAMA_AVX2=OFF -DLLAMA_FMA=OFF -DLLAMA_BUILD_SERVER=OFF ..`
4. `cmake --build . --config Release -j4` (you can change the number due to your cpu cores)
5. Now, you will see a file named `llama.dll` in the folder of `build/bin/Release`. Please put it somewhere of your device and copy its path.
6. Add this line to the beginning of your code: `NativeLibraryConfig.WithLibrary(<path>)`, in which the `<path>` is the path of your compiled `llama.dll`.

If you can't compile it, please feel free to ask us for help.

Finally, since your cpu is not of high performance, please consider set `GpuLayerCount` as large as you can, otherwise the inference speed may be slow.

**Comment by K1tiK4** [comment] 2024-03-17 18:48
Okay, I'll check now

**Comment by AsakusaRinne** [comment] 2024-03-17 18:51
Note: there's already a discussion about supporting different levels of avx in cuda backend #605. If that hits your case, it indicates that it makes sense to support cuda with different avx level. :)

**Comment by K1tiK4** [comment] 2024-03-17 19:01
Yes, this processor does not support avx 2.

**Comment by K1tiK4** [comment] 2024-03-17 19:03
> Note: there's already a discussion about supporting different levels of avx in cuda backend #605. If that hits your case, it indicates that it makes sense to support cuda with different avx level. :)

I think this can help many users

**Comment by K1tiK4** [comment] 2024-03-17 19:16
Unfortunately it didn't help

![image](https://github.com/SciSharp/LLamaSharp/assets/111649965/2ba21d21-9910-45d4-adfa-219c160a5d1c)
![image](https://github.com/SciSharp/LLamaSharp/assets/111649965/2f5f470b-10ed-496d-aec9-d2e3df6fd668)

**Comment by AsakusaRinne** [comment] 2024-03-17 19:18
Could you please run `nvcc -V` to see your cuda version info?

**Comment by K1tiK4** [comment] 2024-03-17 19:37
![image](https://github.com/SciSharp/LLamaSharp/assets/111649965/d1ef3eab-4cf3-43da-adfd-9c023a8e0656)

**Comment by AsakusaRinne** [comment] 2024-03-17 19:50
So weird... Would it be successful if you run llama.cpp examples directly? (instructions could be found in llama.cpp readme file)

**Comment by AsakusaRinne** [comment] 2024-03-17 19:59
> Unfortunately it didn't help
> 
> ![image](https://private-user-images.githubusercontent.com/111649965/313499199-2ba21d21-9910-45d4-adfa-219c160a5d1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDMzMTcsIm5iZiI6MTcxMDcwMzAxNywicGF0aCI6Ii8xMTE2NDk5NjUvMzEzNDk5MTk5LTJiYTIxZDIxLTk5MTAtNDVkNC1hZGZhLTIxOWMxNjBhNWQxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QxOTE2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDY5YzRkNTZlZjY2YTU4MzhmOTViMzZhYWNiZjgxYzExNDMyMTdkOTVlNTAyYWU5YmMyMjQ5Y2RiYWNiMWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TrB3p-cgnSkVNOdvnCpBn8y-T6v57xnbwzs6n6mCFis) ![image](https://private-user-images.githubusercontent.com/111649965/313499201-2f5f470b-10ed-496d-aec9-d2e3df6fd668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDMzMTcsIm5iZiI6MTcxMDcwMzAxNywicGF0aCI6Ii8xMTE2NDk5NjUvMzEzNDk5MjAxLTJmNWY0NzBiLTEwZWQtNDk2ZC1hZWM5LWQyZTNkZjZmZDY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QxOTE2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDJiZDFmYmE2ZDkxYzc3NTkyYTdjZTUxODU4N2Y4M2QwNTM5NjkzNWFjN2NkOWVlY2ZlZjMzZjY3NzYzZGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GiEARX5diACth87Jj6KJdG9QXggqgdr8CGNQ88qA36Y)

A possible fix: could you please uninstall the cuda backend, then delete the `bin` folder of your project and run it again?

**Comment by K1tiK4** [comment] 2024-03-17 20:07
![image](https://github.com/SciSharp/LLamaSharp/assets/111649965/6a357371-52d2-49ba-9471-e6cb9907b932)
llama.cpp works fine

**Comment by K1tiK4** [comment] 2024-03-17 20:10
> > Unfortunately it didn't help
> > ![image](https://private-user-images.githubusercontent.com/111649965/313499199-2ba21d21-9910-45d4-adfa-219c160a5d1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDMzMTcsIm5iZiI6MTcxMDcwMzAxNywicGF0aCI6Ii8xMTE2NDk5NjUvMzEzNDk5MTk5LTJiYTIxZDIxLTk5MTAtNDVkNC1hZGZhLTIxOWMxNjBhNWQxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QxOTE2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDY5YzRkNTZlZjY2YTU4MzhmOTViMzZhYWNiZjgxYzExNDMyMTdkOTVlNTAyYWU5YmMyMjQ5Y2RiYWNiMWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TrB3p-cgnSkVNOdvnCpBn8y-T6v57xnbwzs6n6mCFis) ![image](https://private-user-images.githubusercontent.com/111649965/313499201-2f5f470b-10ed-496d-aec9-d2e3df6fd668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDMzMTcsIm5iZiI6MTcxMDcwMzAxNywicGF0aCI6Ii8xMTE2NDk5NjUvMzEzNDk5MjAxLTJmNWY0NzBiLTEwZWQtNDk2ZC1hZWM5LWQyZTNkZjZmZDY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QxOTE2NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMDJiZDFmYmE2ZDkxYzc3NTkyYTdjZTUxODU4N2Y4M2QwNTM5NjkzNWFjN2NkOWVlY2ZlZjMzZjY3NzYzZGM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GiEARX5diACth87Jj6KJdG9QXggqgdr8CGNQ88qA36Y)
> 
> A possible fix: could you please uninstall the cuda backend, then delete the `bin` folder of your project and run it again?

Yes it helped. Thank you

**Comment by K1tiK4** [comment] 2024-03-17 20:13
![image](https://github.com/SciSharp/LLamaSharp/assets/111649965/ef59cf02-0d95-45e1-84d7-6a2f0735e694)
It loads and exits with code -1073741819

**Comment by K1tiK4** [comment] 2024-03-17 20:16
I changed the library and from the old one (which I did according to the instructions above) a new error
![image](https://github.com/SciSharp/LLamaSharp/assets/111649965/00981aeb-fce5-4854-9c95-0097cc2e1422)

**Comment by AsakusaRinne** [comment] 2024-03-17 20:19
Let's confirm the condition now: you compiled dll yourself, uninstalled cuda12 backend and loaded it with `NativeLibraryConfig.Instance.WithPath`. Is that right?

**Comment by K1tiK4** [comment] 2024-03-17 20:20
> Let's confirm the condition now: you compiled dll yourself, uninstalled cuda12 backend and loaded it with `NativeLibraryConfig.Instance.WithPath`. Is that right?

yes

**Comment by AsakusaRinne** [comment] 2024-03-17 20:22
FYI @martindevans Do you have any idea about it?

**Comment by K1tiK4** [comment] 2024-03-17 20:30
> Поменял библиотеку и со старой (что делал по инструкции выше) новая ошибка ![изображение](https://private-user-images.githubusercontent.com/111649965/313503011-00981aeb-fce5-4854-9c95-0097cc2e1422.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDcwNzgsIm5iZiI6MTcxMDcwNjc3OCwicGF0aCI6Ii8xMTE2NDk5NjUvMzEzNTAzMDExLTAwOTgxYWViLWZjZTUtNDg1NC05Yzk1LTAwOTdjYzJlMTQyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxN1QyMDE5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZGI5Zjc3Y2NiNTY1OWE0NmY4ZjZmZGVjOWI1MGZmMjI4ZTllMGRhMmM0M2MwMWE1ZDhiY2ZkZmFmNDZhY2E4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bnvEtSwDcJzFwByrupumpSEPcQpnql6JiYxIjsLeAHY)

Sorry for the slight confusion
I didn't specify the correct library here.
The console output is different

![image](https://github.com/SciSharp/LLamaSharp/assets/111649965/53938829-ec61-4fdf-b922-8d71e618757d)

**Comment by K1tiK4** [comment] 2024-03-17 20:30
It just breaks after loading the model with code -1073741819

**Comment by martindevans** [comment] 2024-03-17 20:31
Did you compile the DLL from the right version of llama.cpp?

If you're using 0.10.0 it must be _exactly_ this version: https://github.com/ggerganov/llama.cpp/tree/d71ac90985854b0905e1abba778e407e17f9f887

If you're using master it must be exactly this version: ttps://github.com/ggerganov/llama.cpp/tree/3ab8b3a92ede46df88bc5a2dfca3777de4a2b2b6

**Comment by K1tiK4** [comment] 2024-03-17 20:35
Okay, I'll check now

**Comment by K1tiK4** [comment] 2024-03-17 20:49
Oh yes it worked. Thank you
![image](https://github.com/SciSharp/LLamaSharp/assets/111649965/d0957888-e7e0-43d7-a6ab-c12a9c3cfa18)

**Comment by AsakusaRinne** [comment] 2024-03-18 02:16
Close this issue as completed, please feel free to open it again if there's other similar problem.

**Closed by AsakusaRinne** 2024-03-18 02:16 UTC
Labels: bug
