### ISSUE TITLE
Nuget references both CPU and CUDA simultaneously

### ISSUE THREAD

**Issue by xuzeyu91** [SciSharp/LLamaSharp#589] opened 2024-03-11 02:43 UTC
<PackageReference Include="LLamaSharp" Version="0.10.0" />
    <PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.10.0" />
    <PackageReference Include="LLamaSharp.Backend.Cuda12" Version="0.10.0" />
When nuget references both CPU and CUDA simultaneously
```
NativeLibraryConfig
.Instance
.WithCuda(true)
.WithLogs(true);

```
The setting is not effective, GPU inference can only be used when deleting the nuget of the CPU
I hope to use CPU or GPU inference through configuration, rather than letting users reference different nuget packages themselves or load different nuget packages during packaging.
This may be more convenient for users

**Comment by vvdb-architecture** [comment] 2024-03-11 08:32
Probably a duplicate of https://github.com/SciSharp/LLamaSharp/issues/456

**Comment by AsakusaRinne** [comment] 2024-03-11 11:07
Close this issue as a duplicate. please move to #456 and I'll dig at this problem there.

**Closed by AsakusaRinne** 2024-03-11 11:07 UTC
