### ISSUE TITLE
versioning issue

### ISSUE THREAD

**Issue by Barshan-Mandal** [SciSharp/LLamaSharp#900] opened 2024-08-13 14:10 UTC
### Description

please remove this versioning as it becomes too tough to install right package for many nugest as one is dependant on another

**Comment by martindevans** [comment] 2024-08-21 23:11
I'm not sure what you're asking, sorry.

**Comment by Barshan-Mandal** [comment] 2024-08-22 05:30
we now need to use specific version of llamasharp for specific models.
so we cant use updated packages with some packages.
So try making normal versioning which can help tto always use updated packages

**Comment by martindevans** [comment] 2024-08-22 16:19
We do have fairly up to date integrations for kernel memory, if there's a specific issue with them please report it! (I'm not familiar with handlebars planner, looks like it's part of semantic kernel? If so, we have an integration with that too).

**Comment by Barshan-Mandal** [comment] 2024-08-24 14:58
WHY DOES IT FAILS FOR HANDLEBARS PLANNING

**Comment by GalactixGod** [comment] 2024-08-26 17:25
> WHY DOES IT FAILS FOR HANDLEBARS PLANNING

You can't expect a response with this tone of voice.
This is an open source project.
If you want something fixed maybe pay for it?

**Comment by martindevans** [comment] 2024-08-26 17:38
Or contribute a fix of course ;)

Anyway I'm going to close this issue for now. @Barshan-Mandal if you want to open up an issue describing the exact issue, with details to reproduce please go ahead. But keep in mind this is an open source project, and the people who write the code are the people who want that feature to work.

**Closed by martindevans** 2024-08-26 17:38 UTC

**Comment by Barshan-Mandal** [comment] 2024-08-27 06:38
> > WHY DOES IT FAILS FOR HANDLEBARS PLANNING
> 
> You can't expect a response with this tone of voice. This is an open source project. If you want something fixed maybe pay for it?

where should i pay it?.my response was not harse

**Comment by GalactixGod** [comment] 2024-08-27 16:49
> > > WHY DOES IT FAILS FOR HANDLEBARS PLANNING
> > 
> > 
> > You can't expect a response with this tone of voice. This is an open source project. If you want something fixed maybe pay for it?
> 
> where should i pay it?.my response was not harse

You can fix it yourself if you have the skills. 
If you don't and you really want this addressed, then you can hire a developer. 

Take a look at Fiverr, you can hire freelance developers there.

**Comment by martindevans** [comment] 2024-08-27 17:31
To be clear, payment isn't required to take part in this project! But if you're not planning to write the code yourself, you need to provide a clear issue report to help any kind volunteers who want to fix the issue!
